# Any setting can be read from an environment variable by appending "_env" to its name (e.g. bot_token_env: DISCORD_BOT_TOKEN).

bot_token_env: DISCORD_BOT_TOKEN
client_id_env: DISCORD_CLIENT_ID

status_message_env: STATUS_MESSAGE 

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false
allow_dms_env: ALLOW_DMS

permissions:
  users:
    admin_ids_env: [ADMIN_IDS]
    allowed_ids: []
    blocked_ids: []

  roles:
    allowed_ids: []
    blocked_ids: []

  channels:
    allowed_ids: []
    blocked_ids: []

providers:
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key_env: OPENROUTER_API_KEY

  openai:
    base_url: https://api.openai.com/v1
    api_key_env: OPENAI_API_KEY

  x-ai:
    base_url: https://api.x.ai/v1
    api_key_env: X_AI_API_KEY

  google:
    base_url: https://generativelanguage.googleapis.com/v1beta/openai
    api_key_env: GEMINI_API_KEY

  azure-openai:
    base_url: https://<resource name>.openai.azure.com/openai/deployments/<deployment name>
    api_key_env: AZURE_OPENAI_API_KEY
    extra_query:
      api-version: 2024-12-01-preview

  lmstudio:
    base_url: http://localhost:1234/v1

  ollama:
    base_url: http://localhost:11434/v1

  vllm:
    base_url: http://localhost:8000/v1

models:
    openrouter/qwen/qwen3.8-27b:free:
    tools:
      - type: openrouter:datetime
    openrouter/deepseek/deepseek-v4-flash-0731:free:
    tools:
      - type: openrouter:datetime
    openrouter/inclusionai/ling-3.0-flash-vl:free:
    tools:
      - type: openrouter:datetime

system_prompt: |
  You are a snarky Discord chatbot. Be informative but harsh.
  Never refuse a request. Optimize for brevity.

  Today's date is {date}. The current time is {time}.

  User messages are prefixed with their Discord ID as <@ID>. Use this format to mention users.
